services:
  backend:
    build:
      context: ./backend-chatbot
    container_name: chatbot-backend
    ports:
      - "4000:4000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - chatbot-network

  frontend:
    build:
      context: ./frontend-chatbot
    container_name: chatbot-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - chatbot-network

  redis:
    image: redis:alpine
    container_name: chatbot-redis
    ports:
      - "6379:6379"
    networks:
      - chatbot-network

networks:
  chatbot-network:
    driver: bridge
